version: '3.7'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: 827df1f906868ac0c9b2950fdec2c3b2fa2776ee88d93d607ab5fe21b5f92e41dda789903e396109f7c0
        port: 4466
        databases:
          onceapp:
            connector: postgres
            host: db.techst.once
            port: 5432
            user: claptrap
            password: Cl4P-Tp42
            migrations: true
            database: claptrap
    networks:
      techst_network:
        aliases:
          - prisma.techst.once
    depends_on:
      - db
  db:
    image: postgres:10.7
    restart: always
    environment:
      POSTGRES_USER: claptrap
      POSTGRES_PASSWORD: Cl4P-Tp42
    volumes:
      - type: volume
        source: techst_db
        target: /var/lib/postgresql/data
    networks:
      techst_network:
        aliases:
          - db.techst.once
  api:
    environment:
      NODE_ENV: development
      SERVER_PORT: 4000
      PRISMA_SERVER: 'http://prisma.techst.once:4466'
      PRISMA_SERVICE: onceapp
      PRISMA_STAGE: techst
      PRISMA_SECRET: 4ad4c5962600acbe99a5a84096e9fa3c90e8f6bc4783565fba739446148d4e85c7e486160a5fcad64ec7
      PRISMA_MANAGEMENT_API_SECRET: 827df1f906868ac0c9b2950fdec2c3b2fa2776ee88d93d607ab5fe21b5f92e41dda789903e396109f7c0
      APP_SECRET: 892bcb195a65a808cab5f320baceb09be443a48ed57663e844f189f24b51ed95e03e69570d42f1dadb69
      REDIS_HOST: redis.techst.once
      REDIS_PORT: 6379
    build:
      context: .
      dockerfile: ./api.dockerfile
    networks:
      - techst_network
    depends_on:
      - prisma
      - redis
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - 4000:4000
  redis:
    image: redis:5-alpine
    restart: always
    networks:
      techst_network:
        aliases:
          - redis.techst.once

volumes:
  techst_db:

networks:
  techst_network:
